name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 coverage

      - name: Lint with flake8
        run: |
          echo "Running flake8 linting..."
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Run Tests with Coverage
        run: |
          echo "Running tests with coverage..."
          coverage run -m pytest
          coverage report
          coverage html  # Optional: generates HTML report

      # Optional: Deployment Step (Uncomment and customize if needed)
      # - name: Deploy to Streamlit/Render/Heroku
      #   run: |
      #     echo "Deploying application..."
      #     # Example for Streamlit:
      #     # streamlit run app.py

